name: Deploy to ConoHa Wing

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true  # サブモジュールをチェックアウト

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'  # Node.jsのバージョンを変更

      - name: Create .ssh directory and add known hosts
        env:
          HOST: ${{ secrets.HOST }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 $HOST >> ~/.ssh/known_hosts
  
      - name: Install dependencies
        run: npm install
  
      - name: Build project
        run: npm run build
  
      - name: Create deployment directory
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh $USERNAME@$HOST -i private_key -p 22 "mkdir -p collectionassistancetool"

      - name: Stop existing application
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key -p 22 $USERNAME@$HOST "nohup sudo netstat -tuln | grep ':80 ' | awk '{print \$7}' | cut -d'/' -f1 | xargs sudo kill -9"

      - name: Deploy to ConoHa Wing
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          rsync -avz -e "ssh -i private_key -p 22" --exclude node_modules ./ $USERNAME@$HOST:collectionassistancetool
          ssh $USERNAME@$HOST -i private_key -p 22 "cd collectionassistancetool && npm run build && nohup npm run start"
